# Generated by Django 6.0 on 2025-12-18 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('igaveapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='items',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='receipt',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Verification'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='receipt',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
