# Generated by Django 6.0 on 2025-12-18 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('igaveapp', '0003_alter_receipt_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='total_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
