# Generated by Django 6.0 on 2026-01-03 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('igaveapp', '0004_alter_receipt_total_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='category',
            field=models.CharField(choices=[('food', 'Food & Dining'), ('transport', 'Transportation'), ('utilities', 'Utilities'), ('shopping', 'Shopping'), ('entertainment', 'Entertainment'), ('health', 'Health & Fitness'), ('general', 'General')], default='general', max_length=50),
        ),
    ]
